# Generated by Django 5.1.1 on 2024-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("duraion", models.DurationField()),
                ("vid_fle", models.FileField(upload_to="media/videos")),
            ],
        ),
    ]
