# Generated by Django 5.1.1 on 2024-10-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="duraion",
            field=models.IntegerField(),
        ),
    ]
