# Generated by Django 5.1.1 on 2024-10-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_video_duraion"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="audio_file",
            field=models.FileField(blank=True, upload_to="media/audio"),
        ),
        migrations.AlterField(
            model_name="video",
            name="vid_fle",
            field=models.FileField(blank=True, upload_to="media/videos"),
        ),
    ]
